# Generated by Django 4.1.3 on 2022-11-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_distritos_empresas_jornadas_paraderos_rutas_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distritos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='distritos'),
        ),
    ]
